#############################################################################
# Makefile for building: PacketAnalyser
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  PacketAnalyser.pro
# Template: subdirs
# Command: C:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -o Makefile PacketAnalyser.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-types \
		sub-engine \
		sub-ui \
		sub-app


sub-types-qmake_all:  FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd types\ && $(MAKE) -f Makefile qmake_all
sub-types: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-types-make_first-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-types-make_first: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-types-all-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-types-all: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-types-clean-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-types-clean: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-types-distclean-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-types-distclean: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-types-install_subtargets-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-types-install_subtargets: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-types-uninstall_subtargets-ordered: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-types-uninstall_subtargets: FORCE
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-engine-qmake_all: sub-types-qmake_all FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd engine\ && $(MAKE) -f Makefile qmake_all
sub-engine: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-engine-make_first-ordered: sub-types-make_first-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-engine-make_first: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-engine-all-ordered: sub-types-all-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-engine-all: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-engine-clean-ordered: sub-types-clean-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-engine-clean: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-engine-distclean-ordered: sub-types-distclean-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-engine-distclean: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-engine-install_subtargets-ordered: sub-types-install_subtargets-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-engine-install_subtargets: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-engine-uninstall_subtargets-ordered: sub-types-uninstall_subtargets-ordered  FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-engine-uninstall_subtargets: FORCE
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-ui-qmake_all: sub-engine-qmake_all FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd ui\ && $(MAKE) -f Makefile qmake_all
sub-ui: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-ui-make_first-ordered: sub-engine-make_first-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-ui-make_first: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-ui-all-ordered: sub-engine-all-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-ui-all: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-ui-clean-ordered: sub-engine-clean-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-ui-clean: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-ui-distclean-ordered: sub-engine-distclean-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-ui-distclean: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-ui-install_subtargets-ordered: sub-engine-install_subtargets-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-ui-install_subtargets: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-ui-uninstall_subtargets-ordered: sub-engine-uninstall_subtargets-ordered  FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-ui-uninstall_subtargets: FORCE
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-ui-qmake_all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: sub-ui-make_first-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-app-make_first: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-app-all-ordered: sub-ui-all-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-app-all: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: sub-ui-clean-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-app-clean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: sub-ui-distclean-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-app-distclean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: sub-ui-install_subtargets-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: sub-ui-uninstall_subtargets-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: PacketAnalyser.pro C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qdevice.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/angle.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qconfig.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qtquickcompiler.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/lex.prf \
		PacketAnalyser.pro
	$(QMAKE) -o Makefile PacketAnalyser.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qdevice.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/device_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/angle.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/qconfig.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/spec_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/default_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qtquickcompiler.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/yacc.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_64/mkspecs/features/lex.prf:
PacketAnalyser.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile PacketAnalyser.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-types-qmake_all sub-engine-qmake_all sub-ui-qmake_all sub-app-qmake_all FORCE

make_first: sub-types-make_first-ordered sub-engine-make_first-ordered sub-ui-make_first-ordered sub-app-make_first-ordered  FORCE
all: sub-types-all-ordered sub-engine-all-ordered sub-ui-all-ordered sub-app-all-ordered  FORCE
clean: sub-types-clean-ordered sub-engine-clean-ordered sub-ui-clean-ordered sub-app-clean-ordered  FORCE
distclean: sub-types-distclean-ordered sub-engine-distclean-ordered sub-ui-distclean-ordered sub-app-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-types-install_subtargets-ordered sub-engine-install_subtargets-ordered sub-ui-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-types-uninstall_subtargets-ordered sub-engine-uninstall_subtargets-ordered sub-ui-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

sub-types-debug_ordered:
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-engine-debug_ordered: sub-types-debug_ordered 
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-ui-debug_ordered: sub-engine-debug_ordered 
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-app-debug_ordered: sub-ui-debug_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-types-debug_ordered sub-engine-debug_ordered sub-ui-debug_ordered sub-app-debug_ordered

sub-types-release_ordered:
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-engine-release_ordered: sub-types-release_ordered 
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-ui-release_ordered: sub-engine-release_ordered 
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-app-release_ordered: sub-ui-release_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-types-release_ordered sub-engine-release_ordered sub-ui-release_ordered sub-app-release_ordered

sub-types-check_ordered:
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-engine-check_ordered: sub-types-check_ordered 
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-ui-check_ordered: sub-engine-check_ordered 
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-app-check_ordered: sub-ui-check_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-types-check_ordered sub-engine-check_ordered sub-ui-check_ordered sub-app-check_ordered

sub-types-benchmark_ordered:
	@if not exist types\ mkdir types\ & if not exist types\ exit 1
	cd types\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\types\types.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-engine-benchmark_ordered: sub-types-benchmark_ordered 
	@if not exist engine\ mkdir engine\ & if not exist engine\ exit 1
	cd engine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\engine\engine.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-ui-benchmark_ordered: sub-engine-benchmark_ordered 
	@if not exist ui\ mkdir ui\ & if not exist ui\ exit 1
	cd ui\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\ui\ui.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-app-benchmark_ordered: sub-ui-benchmark_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Myacc\OneDrive\Desktop\QtProjects\packet-analyser-master\app\app.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-types-benchmark_ordered sub-engine-benchmark_ordered sub-ui-benchmark_ordered sub-app-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

