######################################################################
# Automatically generated by qmake (3.1) Sat Jul 18 23:39:59 2020
######################################################################

TEMPLATE = lib
TARGET = types
DESTDIR = ../lib
INCLUDEPATH += .
MOC_DIR = ../generated/moc
OBJECTS_DIR = ../generated/obj


# Input
HEADERS += ArrayTypeObject.h Object.h TypeObject.h
SOURCES += ArrayTypeObject.cpp Object.cpp TypeObject.cpp
